2 update to v1.8.0
alttester-test-examples/CSharp-Standalone-AltTrashCat pull request #2
Opened 2022-10-21 14:21 UTC by SandyEma9

@robert-altom @RobertPoienar  @gomboskriszta15 @iulianatodoran

2022-10-21 16:06 UTC, iulianatodoran reviewed
**Update: not occurring anymore**

For Windows all good, but for Mac, 6 tests fail, this is the output from the terminal in VSCode:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestPlayerDiesWhenObstacleNotAvoided [5 s]
  Error Message:
   Altom.AltUnityDriver.AltUnityException : Driver disconnected
  Stack Trace:
     at Altom.AltUnityDriver.Commands.DriverCommunicationWebSocket.Recvall[T](CommandParams param)
   at Altom.AltUnityDriver.Commands.AltUnityFindObject.Execute()
   at Altom.AltUnityDriver.Commands.AltUnityWaitForObject.Execute()
   at Altom.AltUnityDriver.AltUnityDriver.WaitForObject(By by, String value, By cameraBy, String cameraValue, Boolean enabled, Double timeout, Double interval)
   at alttrashcat_tests_csharp.pages.GetAnotherChancePage.get_GameOverButton() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/pages/GetAnotherChancePage.cs:line 11
   at alttrashcat_tests_csharp.pages.GetAnotherChancePage.IsDisplayed() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/pages/GetAnotherChancePage.cs:line 17
   at alttrashcat_tests_csharp.tests.GamePlayTests.TestPlayerDiesWhenObstacleNotAvoided() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/tests/GamePlayTests.cs:line 71
  Standard Output Messages:
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Send|This operation isn't available in: closed
 21/10/2022 19:01:52|Error|WebSocket.Close|This operation isn't available in: closed


^CAttempting to cancel the build...
==>Kill app
No matching processes belonging to you were found
iuliana.todoran@altom-mac6 CSharp-Standalone-AltTrashCat % ./start_tests_Mac.sh
==> Open application
==>Wait for application to start
==>Restore test project and run tests
  Determining projects to restore...
/Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/TestAlttrashCSharp.csproj : warning NU1701: Package 'Unity3D.UnityEngine 2018.3.5.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/TestAlttrashCSharp.csproj : warning NU1701: Package 'WebSocketSharp 1.0.3-rc11' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  Restored /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/TestAlttrashCSharp.csproj (in 1.96 sec).
/Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/TestAlttrashCSharp.csproj : warning NU1701: Package 'Unity3D.UnityEngine 2018.3.5.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/TestAlttrashCSharp.csproj : warning NU1701: Package 'WebSocketSharp 1.0.3-rc11' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  TestAlttrashCSharp -> /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/bin/Debug/netcoreapp3.1/TestAlttrashCSharp.dll
Test run for /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/bin/Debug/netcoreapp3.1/TestAlttrashCSharp.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestAvoidingObstacles [2 s]
  Error Message:
   Altom.AltDriver.NullReferenceException : Object reference not set to an instance of an object
  Stack Trace:
     at Altom.AltDriver.Commands.DriverCommunicationWebSocket.handleErrors(CommandError error)
   at Altom.AltDriver.Commands.DriverCommunicationWebSocket.Recvall[T](CommandParams param)
   at Altom.AltDriver.Commands.AltCommandReturningAltElement.ReceiveAltObject(CommandParams cmdParams)
   at Altom.AltDriver.Commands.AltTapElement.Execute()
   at Altom.AltDriver.AltObject.Tap(Int32 count, Single interval, Boolean wait)
   at alttrashcat_tests_csharp.pages.MainMenuPage.PressRun() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/pages/MainMenuPage.cs:line 30
   at alttrashcat_tests_csharp.tests.GamePlayTests.Setup() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/tests/GamePlayTests.cs:line 23
  Standard Output Messages:
 2022-10-21 19:02:23.1184|INFO|Info
 2022-10-21 19:02:23.1766|INFO|AltTester logs are saved at: ./AltTester.log


  Failed TestGameCanBePausedAndResumed [1 s]
  Error Message:
   Altom.AltDriver.NullReferenceException : Object reference not set to an instance of an object
  Stack Trace:
     at Altom.AltDriver.Commands.DriverCommunicationWebSocket.handleErrors(CommandError error)
   at Altom.AltDriver.Commands.DriverCommunicationWebSocket.Recvall[T](CommandParams param)
   at Altom.AltDriver.Commands.AltCommandReturningAltElement.ReceiveAltObject(CommandParams cmdParams)
   at Altom.AltDriver.Commands.AltTapElement.Execute()
   at Altom.AltDriver.AltObje [...]

2022-10-27 06:42 UTC, iulianatodoran commented on README.md
> +    The app is provided at https://altom.com/app/uploads/AltTester/TrashCat/TrashCatMacOS.zip and needs to be included  unzipped under the App/TrashCatMac/ folder.
Change the Mac download link to https://altom.com/app/uploads/AltTester/TrashCat/TrashCatMacOS.app.zip since the zip file was changed

2022-10-27 06:43 UTC, iulianatodoran commented on README.md
> +    The app is provided at https://altom.com/app/uploads/AltTester/TrashCat/TrashCatMacOS.zip and needs to be included  unzipped under the App/TrashCatMac/ folder.
remove 1 space between `included` and `unzipped`

2022-10-27 06:44 UTC, iulianatodoran commented on README.md
> +    The app is provided at https://altom.com/app/uploads/AltTester/TrashCat/TrashCatWindows.zip and needs to be included  unzipped under the App/TrashCatWindows/ folder.
remove 1 space between `included` and `unzipped`

2022-10-27 07:17 UTC, RobertPoienar requested changes
Minor change in ReadME, rest looks fine to me

2022-10-27 07:17 UTC, RobertPoienar commented on README.md
> +**This project already has the AltDriver inside, but otherwise would require to add https://www.nuget.org/packages/AltDriver package in order to work.**
The correct link is the following: https://www.nuget.org/packages/AltTester-Driver

2022-10-27 07:24 UTC, iulianatodoran commented
1 test fails on Mac, here is the log:
total of 1 test files matched the specified pattern.
```
  Failed TestAvoidingObstacles [27 s]
  Error Message:
   System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
  Stack Trace:
     at System.Collections.Generic.List`1.get_Item(Int32 index)
   at alttrashcat_tests_csharp.pages.GamePlay.AvoidObstacles(Int32 numberOfObstacles) in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/pages/GamePlay.cs:line 44
   at alttrashcat_tests_csharp.tests.GamePlayTests.TestAvoidingObstacles() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/tests/GamePlayTests.cs:line 52
```

2022-10-27 07:29 UTC, iulianatodoran commented on README.md
> +- `./start_tests_Windows.sh`./start_tests_windows.sh on Windows
delete the duplication **./start_tests_windows.sh** after the quoted command

2022-10-27 08:29 UTC, RobertPoienar approved these changes
LGTM

2022-10-27 08:41 UTC, iulianatodoran commented
> 1 test fails on Mac, here is the log:
> 
> ```
> total of 1 test files matched the specified pattern.
>   Failed TestAvoidingObstacles [27 s]
>   Error Message:
>    System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>   Stack Trace:
>      at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at alttrashcat_tests_csharp.pages.GamePlay.AvoidObstacles(Int32 numberOfObstacles) in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/pages/GamePlay.cs:line 44
>    at alttrashcat_tests_csharp.tests.GamePlayTests.TestAvoidingObstacles() in /Users/iuliana.todoran/AltUnity/examples/Examples with ATUSDK/CSharp-Standalone-AltTrashCat/TestAlttrashCSharp/tests/GamePlayTests.cs:line 52
> ```

The test itself fails sometimes because the Cat character dies exactly at the end of the test so will pass on this

2022-10-27 08:42 UTC, iulianatodoran approved these changes
LGTM

2022-10-27 08:42 UTC, merged